# If you are editing this file inside /etc/pipelam/pipelam.toml please refain from doing that - you can override the
# default config by creating a file in ~/.config/pipelam/pipelam.toml. The file /etc/pipelam/pipelam.toml will be
# deleted during the unintall process
log_level = INFO # The log level for the application; INFO means the application will log all messages; DEBUG means the
                 # application will log all messages including debug messages; WARNING means the application will log all
                 # messages including warning messages; ERROR means the application will log all messages including error
                 # messages; PANIC means the application will log all messages including panic messages. (Default: INFO)
runtime_behaviour = replace # The runtime behaviour of gtk windows; replace means the windows are replaced; queue means
                            # the windows are queued and displayed one after the other;  overlay means the windows are
                            # overlayed on top of each other. (Default: replace)
window_timeout = 600 # The time in milliseconds before the overlay is hidden. (Default: 600) (Can be overridden by the JSON payload)
anchor = center # The anchor point of the overlay; center means the overlay is centered on the screen; top-left means the
                # overlay is anchored to the top left corner of the screen; top-right means the overlay is anchored to the
                # top right corner of the screen; bottom-left means the overlay is anchored to the bottom left corner of
                # the screen; bottom-right means the overlay is anchored to the bottom right corner of the screen.
                # (Default: center) (Can be overridden by the JSON payload)
margin_left = 100 # The margin from the left edge of the screen. (Default: 100) (Can be overridden by the JSON payload)
margin_right = 0 # The margin from the right edge of the screen. (Default: 0) (Can be overridden by the JSON payload)
margin_top = 100 # The margin from the top edge of the screen. (Default: 100) (Can be overridden by the JSON payload)
margin_bottom = 0 # The margin from the bottom edge of the screen. (Default: 0) (Can be overridden by the JSON payload)
