log_level = INFO # The log level for the application. (Default: "INFO")
runtime_behaviour = queue # The runtime behaviour of gtk windows; queue means the windows are queued and displayed one after the other; replace means the windows are replaced; overlay means the windows are overlayed on top of each other. (Default: "queue")
window_timeout = 600 # The time in milliseconds before the overlay is hidden. (Default: 600) (Can be overridden by the JSON payload)
anchor = center # The anchor point of the overlay. (Default: "center") (Can be overridden by the JSON payload)
margin_left = 100 # The margin from the left edge of the screen. (Default: 100) (Can be overridden by the JSON payload)
margin_right = 0 # The margin from the right edge of the screen. (Default: 0) (Can be overridden by the JSON payload)
margin_top = 100 # The margin from the top edge of the screen. (Default: 100) (Can be overridden by the JSON payload)
margin_bottom = 0 # The margin from the bottom edge of the screen. (Default: 0) (Can be overridden by the JSON payload)
