name: Pull Request Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtk-4-dev libgtk-layer-shell-dev wayland-protocols meson ninja-build libwayland-dev wayland-protocols libgtk-4-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools python3 valac scdoc
          git clone https://github.com/wmww/gtk4-layer-shell.git && cd gtk4-layer-shell
          meson setup -Dexamples=true -Ddocs=true -Dtests=true build
          ninja -C build
          sudo ninja -C build install
          sudo ldconfig

      - name: Build project
        run: make

      - name: Run tests
        run: make test

      - name: Build man pages
        run: make docs

      - name: Report test status
        if: success()
        run: echo "All tests completed successfully! ✅"

